-- V1 establishes the migration baseline only.
--
-- Applying it creates Flyway's schema history table and proves the migration
-- pipeline works end to end. No FAPP domain tables are defined yet: the unified
-- transaction model is designed first, then introduced in V2 onwards.
--
-- Rules for every future migration in this project:
--   * migrations are versioned, forward-only and never edited once applied;
--   * the schema is defined here in SQL, never generated by Hibernate.

SELECT 1;
